### ISSUE TITLE
Disable input on multiplayer game

### ISSUE THREAD

**Issue by krazyjakee** [expressobits/character-controller#13]
Hi there,
I'm developing a multiplayer game.

I only want the character-controller to be controllable when the current instance is the authority. To achieve this, I'd like a simple switch to enable and disable input across the entire node.

Thanks

**Comment by scriptsengineer** [comment]
This controller was already thinking about it, remember that the player is a code that must be changed and used in a customized way by the user:

In the example below the input is only processed to be used when mouse is being captured, however it can be changed to include checking if the local player is authoritative or not

```gdscript
func _physics_process(delta):
	var is_valid_input := Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED
	
	if is_valid_input:
		if Input.is_action_just_pressed(input_fly_mode_action_name):
			fly_ability.set_active(not fly_ability.is_actived())
		var input_axis = Input.get_vector(input_back_action_name, input_forward_action_name, input_left_action_name, input_right_action_name)
		var input_jump = Input.is_action_just_pressed(input_jump_action_name)
		var input_crouch = Input.is_action_pressed(input_crouch_action_name)
		var input_sprint = Input.is_action_pressed(input_sprint_action_name)
		var input_swim_down = Input.is_action_pressed(input_crouch_action_name)
		var input_swim_up = Input.is_action_pressed(input_jump_action_name)
		move(delta, input_axis, input_jump, input_crouch, input_sprint, input_swim_down, input_swim_up)
	else:
		move(delta)
```

> NOTE: It is worth remembering that some multiplayer games simply do not process the controller when remote, so the check must be at a higher level, preventing the so-called move from happening
