### ISSUE TITLE
Implement an "escape mouse capture" key binding.

### ISSUE THREAD

**Issue by des1redState** [expressobits/character-controller#14]
Title says it all really, it'd be great to have support for, for example, hitting Esc and releasing mouse control back to the OS.

**Comment by scriptsengineer** [comment]
This already exists, but it is not the 'Esc' key but the 'Tab' key, it can be changed in the settings.
![image](https://user-images.githubusercontent.com/1673249/220451183-cf7aabc4-bdf0-482e-96a9-d79618d7459c.png)
![image](https://user-images.githubusercontent.com/1673249/220451274-5e154f46-b3c4-4219-b3c5-12d9e1a4c571.png)

**Comment by des1redState** [comment]
Oh, so it does! In that case, apologies for the spam and thank you for your awesome contribution to the Godot community!
