### ISSUE TITLE
Name is "Inventory System" in AssetLib

### ISSUE THREAD

**Issue by spacehare** [expressobits/character-controller#23]
![Godot_v4 1 1-stable_mono_win64_a4UyW36P3j](https://github.com/expressobits/character-controller/assets/38092970/7b15fff2-5142-40ae-82cc-5582524e3a68)

**Comment by scriptsengineer** [comment]
I had a problem copying the CI workflow from the other addon, but it has currently been fixed and awaiting asset lib approval.
I will close this issue only after approval.
