### ISSUE TITLE
Missing setting mouse capture as default in player.gd

### ISSUE THREAD

**Issue by rtizzy** [expressobits/character-controller#6]
Very cool script. I'm a complete noobie at Godot. Sorry if this should be apparent. 

I am able to open the level.tscn, map controls, and move around. 

The problem arises when trying to add the character controller to my own project. 

I've tried a few things in an attempt to replicate the example but none of them seem to work. 

1. Just copying over player.tscn from the example to my own world. 
2. Creating an inherited scene of `fps/fps_controller3d.tscn`, saving it as player, importing that into my own world, and copying the script attached to `player.tscn` to my own player scene. 

A bit stumped.

**Comment by scriptsengineer** [comment]
Thanks for opening the error and asking, I ended up noticing an oversight on my part, in the configuration step your project needs to capture the mouse at least for proper operation of player.gd inputs.
- Put this code at the beginning of the execution of your project, it activates the capture of the mouse and hides it.
Input.mouse_mode = Input.MOUSE_MODE_CAPTURED

**Comment by rtizzy** [comment]
@scriptsengineer To clarify, I am not seeing the error you are referring to. 

My issue is related to usage of the project. 

I.E This provides functionality to offer a player controller but it's unclear of how to use that controller in my own project. I've checked the docs here as well as the Godot Docs.

**Comment by scriptsengineer** [comment]
Does he just not walk?

**Comment by rtizzy** [comment]
The errors I'm seeing range from "Will completely crash" to "won't walk and isn't effected by gravity". 

I've also tried adding `CharacterController3D` and `FPSController3d` and `player` as it's own node but that doesn't seem to work either :( 

![image](https://user-images.githubusercontent.com/523926/214998114-666349a7-06ca-4a38-aadb-e55b33438879.png)

![image](https://user-images.githubusercontent.com/523926/214998177-000e70b5-cdbc-4b2f-9920-a52eae115578.png)

I can make a video if that's easier.

**Comment by rtizzy** [comment]
I'm just starting from a barebones world with a floor and trying to add a character with movement managed by the FPSController3d

**Comment by scriptsengineer** [comment]
https://user-images.githubusercontent.com/1673249/214998854-c263efaf-ccb0-419c-b3d3-65b795b18089.mp4
See if this can help

**Comment by scriptsengineer** [comment]
The version I am using is godot 4 beta 14

**Comment by rtizzy** [comment]
I'm on beta 15, with that said that completely fixed the issue. Sorry for the confusion :). 

```
Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
```

Thank you!

**Comment by scriptsengineer** [comment]
Fixed in 2.1.3
