### ISSUE TITLE
Intended way to expand the controller? 

### ISSUE THREAD

**Issue by rtizzy** [expressobits/character-controller#7]
So not sure if this is more "Godot" related or addonrelated. Might need to RTFM :P. 

How would one go about adding their own inputs to this (For example, left click to shoot)

So in a previous issue it was found you can import and use the `Player` scene, which handles various input mappings. 

I can see that it is possible to extend a particular script within Godot. 

Should you be extending the `Player` scene/script or instead, writing your own `Player` and then extending the FPSController? 

I would imagine it's the latter as if you attempt to write 

```
func _physics_process(delta):
    #Your code here
    pass
```

Then this will just overwrite everything in the existing player.gd provided by this addon.

**Comment by scriptsengineer** [comment]
The idea of `player.gd` is to be an example to be followed, that is, it must be edited/created by the user

**Comment by rtizzy** [comment]
Thanks. I was able to continue expanding on things thanks to your advice. 

I know you're likely to get a lot of newbies like me who have no idea what they are doing and it would be good to expand upon this in the documentation. 

I'd have added this myself but I'm not able to edit the wiki. 

Would it be possible to provide a path for contributors to edit the documentation? I'd be happy to contribute but don't have a way to do so currently. 

I'll create a separate card for that.
