### ISSUE TITLE
Broken in Beta 16

### ISSUE THREAD

**Issue by MarkReiland** [expressobits/character-controller#8]
With all of the compatibility changes in beta 16, a lot seems to have broken with the character controller. I created a new project, imported the addon, enabled it, set the level scene as the main scene, and then ran it and got this: 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/80435916/215258399-07a47ae9-b0ad-41b0-8663-991f978156b3.png">

In another existing project where I previously installed the addon and had it working, I get these "Parser Error: Argument 1 of annotation "@export_node_path" isn't a constant expression." errors everywhere there's an "@export_node_path".
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/80435916/215258598-59f9d0be-1f19-4a3a-9f79-6b69c42f6df3.png">

Edit: The issue with the "@export_node_paths" is that quotes are now required on the annotations. See [this PR](https://github.com/godotengine/godot/pull/71634) for more info on the change.

Wasn't able to find which change in beta 16 is causing all of these errors, but hopefully there's an easy fix.

**Comment by scriptsengineer** [comment]
Fixed in 2.1.3
