### ISSUE TITLE
Allow Contributors to modify (or ask to modify) documentation. 

### ISSUE THREAD

**Issue by rtizzy** [expressobits/character-controller#9]
Currently there is no way for a third party contributor to provide updates to the documentation. 

User Story: 

1. I am a library user who just learned something on my own or with the help of the maintainers
2. I would like to provide updates to the documentation to help others. 
3. I make an update to the documentation to inform library users of this information. 

What the maintainers might want:

1. A maintainer would like contributors to provide updates to documentation. 
2. A maintainer would like to review contributions to documentation before allowing them to go live. 
3. A maintainer would like this process to be as seamless and pain free as possible. 

There are multiple ways this could be handled but I'm uncertain if Github Wiki will allow the needed permissions for a suitable strategy. 

As an example see the [following issue](https://github.com/expressobits/character-controller/issues/7).

A look at the [GH Wiki documentation](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis) seems to demonstrate that it can be only certain people or all people who can make modifications. This may or may not be desirable. 

Suggested Action:

1. Implement a wiki or documentation system that can be modified via the standard PR workflow. The documentation is created and updated via code. 
2. Implement a basic CI pipeline to update the documentation.

**Comment by scriptsengineer** [comment]
There really was an option to restrict document editing which has now been disabled,
I'm currently working on another feature [https://github.com/expressobits/inventory-system](https://github.com/expressobits/inventory-system)
But my idea is to create a more complete documentation about the addon.

**Comment by scriptsengineer** [comment]
Added new issue to track code tutorials and documentation #10
